---
title: "Code for Assessing Teacher Competence with Situational Judgement Test Generated by Large Language Models"
output: html_document
date: "2024-10-24"
---

```{r scenarios}

library(openxlsx)
library(dplyr)
library(textTinyR)
library(plotly)
library(ggplot2)
library(gridExtra)
library(lavaan)
library(psych)
library(Hmisc)
library(tidyr)

#-------ICC-------

# Problem Solving

autenticity_ICC<-read.xlsx('PS_authenticity.xlsx')

psych::ICC(autenticity_ICC[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8")]) # 0.72

typicality_ICC<-read.xlsx('PS_typicality.xlsx')

psych::ICC(typicality_ICC[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8")]) # 0.75

# Student Orientation

autenticity_ICC<-read.xlsx('SO_authenticity.xlsx')

psych::ICC(autenticity_ICC[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8")]) # 0.52

typicality_ICC<-read.xlsx('SO_typicality.xlsx')

psych::ICC(typicality_ICC[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8")]) # 0.52


#-------compare 3 tests-------

# Problem Solving

autenticity_PS <-read.xlsx('PS_authenticity.xlsx')

PS_autenticity <- autenticity_PS %>%
  group_by(group) %>%
  summarise(
    Mean = mean(authenticity, na.rm = TRUE), 
    SD = sd(authenticity, na.rm = TRUE),     
    Max = max(authenticity, na.rm = TRUE),   
    Min = min(authenticity, na.rm = TRUE)   
  )

p_PS_aut <- ggplot(autenticity_PS, aes(x = authenticity, fill = group)) + 
  geom_density(alpha = 0.5, adjust = 1) + 
  scale_fill_manual(values = c("original" = "#00CED1", "new" = "#EE82EE", "adapted" ="#4169E1"), 
                    limits = c("original", "new", "adapted")) + 
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.2)) +  
  scale_x_continuous(limits = c(1, 5), breaks = seq(1, 5, by = 1)) +
  theme_minimal() +
  theme(
     legend.position = "none",  
    panel.grid = element_blank()  
  )


typicality_PS <-read.xlsx('PS_typicality.xlsx')

PS_typicality <- typicality_PS %>%
  group_by(group) %>%
  summarise(
    Mean = mean(typicality, na.rm = TRUE), 
    SD = sd(typicality, na.rm = TRUE),     
    Max = max(typicality, na.rm = TRUE),    
    Min = min(typicality, na.rm = TRUE)    
  )

p_PS_typ <- ggplot(typicality_PS, aes(x = typicality, fill = group)) + 
  geom_density(alpha = 0.5, adjust = 1) +  
  scale_fill_manual(values = c("original" = "#00CED1", "new" = "#EE82EE", "adapted" ="#4169E1"), 
                    limits = c("original", "new", "adapted")) +  
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.2)) +  
  scale_x_continuous(limits = c(1, 5), breaks = seq(1, 5, by = 1)) +
  theme_minimal() +
  theme(
     legend.position = "none",  
    panel.grid = element_blank()  
  )


#Student Orientation 

autenticity_SO <-read.xlsx('SO_authenticity.xlsx')

SO_autenticity <- autenticity_SO %>%
  group_by(group) %>%
  summarise(
    Mean = mean(authenticity, na.rm = TRUE), 
    SD = sd(authenticity, na.rm = TRUE),     
    Max = max(authenticity, na.rm = TRUE),   
    Min = min(authenticity, na.rm = TRUE)   
  )

p_SO_aut <- ggplot(autenticity_SO, aes(x = authenticity, fill = group)) + 
  geom_density(alpha = 0.5, adjust = 1) + 
  scale_fill_manual(values = c("original" = "#00CED1", "new" = "#EE82EE", "adapted" ="#4169E1"), 
                    limits = c("original", "new", "adapted")) + 
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.2)) +  
  scale_x_continuous(limits = c(1, 5), breaks = seq(1, 5, by = 1)) +
  theme_minimal() +
  theme(
     legend.position = "none",  
    panel.grid = element_blank()  
  )

typicality_SO <- read.xlsx('SO_typicality.xlsx')

result_typ <- typicality_SO %>%
  group_by(group) %>%
  summarise(
    Mean = mean(typicality, na.rm = TRUE), 
    SD = sd(typicality, na.rm = TRUE),     
    Max = max(typicality, na.rm = TRUE),    
    Min = min(typicality, na.rm = TRUE)    
  )

p_SO_typ <- ggplot(typicality_SO, aes(x = typicality, fill = group)) + 
  geom_density(alpha = 0.5, adjust = 1) +  
  scale_fill_manual(values = c("original" = "#00CED1", "new" = "#EE82EE", "adapted" = "#4169E1"), 
                    limits = c("original", "new", "adapted")) +  
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.2)) +  
  scale_x_continuous(limits = c(1, 5), breaks = seq(1, 5, by = 1)) +
  theme_minimal() +
  theme(
    legend.position = "right",  
    panel.grid = element_blank(),
    legend.key.size = unit(0.4, "cm") 
  )


grid.arrange(p_PS_aut,p_PS_typ,p_SO_aut,p_SO_typ,ncol=4)

#-------change in rounds-------

# PS

autenticity_PS <-read.xlsx('PS_authenticity.xlsx')

data_summary1 <- autenticity_PS %>%
  filter(round != "none") %>%  
  group_by(round, group) %>%
  summarise(
    mean = mean(authenticity , na.rm = TRUE), 
    min = min(authenticity , na.rm = TRUE),    
    max = max(authenticity , na.rm = TRUE),  
    .groups = 'drop'  
  )

p1 <- ggplot(data_summary1, aes(x = round, y = mean, group = group, color = group)) +
  geom_line(linewidth = 1.5) +  
  geom_ribbon(aes(ymin = min, ymax = max, fill = group), color = NA, alpha = 0.2) + 
  geom_point(size = 2) +
  scale_color_manual(values = c("new" = "#EE82EE", "adapted" = "#4169E1"), limits = c("new", "adapted")) +
  scale_fill_manual(values = c("new" = "#EE82EE", "adapted" = "#4169E1"), limits = c("new", "adapted")) +  
  theme_minimal() +
  scale_y_continuous(limits = c(2, 5)) +
  scale_x_discrete(labels = c("round1", "round2", "round3")) + 
  labs(x = NULL, y = "Authenticity") +  
  theme(
    legend.position = "none",
    axis.text.x = element_text(size = 10,angle = 45, hjust = 1),  
    axis.text.y = element_text(size = 10)  
  )


typicality_PS <-read.xlsx('PS_typicality.xlsx')

data_summary2 <- typicality_PS %>%
  filter(round != "none") %>%  
  group_by(round, group) %>%
  summarise(
    mean = mean(typicality , na.rm = TRUE),  
    min = min(typicality , na.rm = TRUE),   
    max = max(typicality , na.rm = TRUE),  
    .groups = 'drop' 
  )

p2 <- ggplot(data_summary2, aes(x = round, y = mean, group = group, color = group)) +
  geom_line(linewidth = 1.5) +  
  geom_ribbon(aes(ymin = min, ymax = max, fill = group), color = NA, alpha = 0.2) + 
  geom_point(size = 2) +
  scale_color_manual(values = c("new" = "#EE82EE", "adapted" = "#4169E1"), limits = c("new", "adapted")) +
  scale_fill_manual(values = c("new" = "#EE82EE", "adapted" = "#4169E1"), limits = c("new", "adapted")) +  
  theme_minimal() +
  scale_y_continuous(limits = c(2, 5)) +
  scale_x_discrete(labels = c("round1", "round2", "round3")) + 
  labs(x = NULL, y = "Typicality") +  
  theme(
    legend.position = "none",
    axis.text.x = element_text(size = 10,angle = 45, hjust = 1),  
    axis.text.y = element_text(size = 10)  
  )


# SO

autenticity_SO <-read.xlsx('SO_authenticity.xlsx')

data_summary3 <- autenticity_SO %>%
  filter(round != "none") %>%  
  group_by(round, group) %>%
  summarise(
    mean = mean(authenticity , na.rm = TRUE), 
    min = min(authenticity , na.rm = TRUE),    
    max = max(authenticity , na.rm = TRUE),  
    .groups = 'drop'  
  )

p3 <- ggplot(data_summary3, aes(x = round, y = mean, group = group, color = group)) +
  geom_line(linewidth = 1.5) +  
  geom_ribbon(aes(ymin = min, ymax = max, fill = group), color = NA, alpha = 0.2) + 
  geom_point(size = 2) +
  scale_color_manual(values = c("new" = "#EE82EE", "adapted" = "#4169E1"), limits = c("new", "adapted")) +
  scale_fill_manual(values = c("new" = "#EE82EE", "adapted" = "#4169E1"), limits = c("new", "adapted")) +  
  theme_minimal() +
  scale_y_continuous(limits = c(2, 5)) +
  scale_x_discrete(labels = c("round1", "round2", "round3")) + 
  labs(x = NULL, y = "Authenticity") +  
  theme(
    legend.position = "none",
    axis.text.x = element_text(size = 10,angle = 45, hjust = 1),  
    axis.text.y = element_text(size = 10)  
  )


typicality_SO <-read.xlsx('SO_typicality.xlsx')

data_summary4 <- typicality_SO %>%
  filter(round != "none") %>%  
  group_by(round, group) %>%
  summarise(
    mean = mean(typicality , na.rm = TRUE),  
    min = min(typicality , na.rm = TRUE),   
    max = max(typicality , na.rm = TRUE),  
    .groups = 'drop' 
  )

p4 <- ggplot(data_summary4, aes(x = round, y = mean, group = group, color = group)) +
  geom_line(linewidth = 1.5) +  
  geom_ribbon(aes(ymin = min, ymax = max, fill = group), color = NA, alpha = 0.2) + 
  geom_point(size = 2) +
  scale_color_manual(values = c("new" = "#EE82EE", "adapted" = "#4169E1"), limits = c("new", "adapted")) +
  scale_fill_manual(values = c("new" = "#EE82EE", "adapted" = "#4169E1"), limits = c("new", "adapted")) +  
  theme_minimal() +
  scale_y_continuous(limits = c(2, 5)) +
  scale_x_discrete(labels = c("round1", "round2", "round3")) + 
  labs(x = NULL, y = "Typicality") +  
  theme(
    legend.position = "none",
    axis.text.x = element_text(size = 10,angle = 45, hjust = 1),  
    axis.text.y = element_text(size = 10)  
  )

grid.arrange(p1,p2,p3,p4,ncol=4)

```


```{r new options}

optiondata<-read.xlsx('PS_new_options.xlsx')

item1 <- subset(optiondata, ID == "new_r1_1")
psych::ICC(item1[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.98

item2 <- subset(optiondata, ID == "new_r1_2")
psych::ICC(item2[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.98

item3 <- subset(optiondata, ID == "new_r1_3")
psych::ICC(item3[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.96

item4 <- subset(optiondata, ID == "new_r1_4")
psych::ICC(item4[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.98

item5 <- subset(optiondata, ID == "new_r1_5")
psych::ICC(item5[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.98

item6 <- subset(optiondata, ID == "new_r1_6")
psych::ICC(item6[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.98

item7 <- subset(optiondata, ID == "new_r2_1")
psych::ICC(item7[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.99

item8 <- subset(optiondata, ID == "new_r2_2")
psych::ICC(item8[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.98

item9 <- subset(optiondata, ID == "new_r2_3")
psych::ICC(item9[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.99

item10 <- subset(optiondata, ID == "new_r2_4")
psych::ICC(item10[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.98

item11 <- subset(optiondata, ID == "new_r2_5")
psych::ICC(item11[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.99

item12 <- subset(optiondata, ID == "new_r2_6")
psych::ICC(item12[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.99

item13 <- subset(optiondata, ID == "new_r3_1")
psych::ICC(item13[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.99

item14 <- subset(optiondata, ID == "new_r3_2")
psych::ICC(item14[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.97

item15 <- subset(optiondata, ID == "new_r3_3")
psych::ICC(item15[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.98

item16 <- subset(optiondata, ID == "new_r3_4")
psych::ICC(item16[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.98

item17 <- subset(optiondata, ID == "new_r3_5")
psych::ICC(item17[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.99

item18 <- subset(optiondata, ID == "new_r3_6")
psych::ICC(item18[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.98

optiondata <- optiondata %>%
  group_by(ID) %>%
  mutate(
    rank = row_number(mean) 
  ) %>%
  ungroup()

#write.xlsx(optiondata,file='sorted_option.xlsx')

prob_high <- numeric(18)
prob_medium <- numeric(18)
prob_low <- numeric(18)

for (i in 1:18) {
  current_item <- subset(optiondata, itemID == paste0("item", i))
  current_item <- current_item[order(current_item$rank), ]  
  current_item$expert_score <- c(2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0)  
  current_item <- current_item[order(current_item$LLM), ]  
  current_item$LLM_score <- c(2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0)
  
  high_score_items <- subset(current_item, LLM_score == 2)
  matching_high <- sum(high_score_items$expert_score == 2)  
  prob_high[i] <- matching_high / nrow(high_score_items)
  
  medium_score_items <- subset(current_item, LLM_score == 1)
  matching_medium <- sum(medium_score_items$expert_score == 1)  
  prob_medium[i] <- matching_medium / nrow(medium_score_items)
  
  low_score_items <- subset(current_item, LLM_score == 0)
  matching_low <- sum(low_score_items$expert_score == 0)  
  prob_low[i] <- matching_low / nrow(low_score_items)
}

prob_high_df <- as.data.frame(prob_high)
prob_medium_df <- as.data.frame(prob_medium)
prob_low_df <- as.data.frame(prob_low)

consistency_results <- data.frame(
  itemID = paste0("item", 1:18),
  high_score_consistency = prob_high,
  medium_score_consistency = prob_medium,
  low_score_consistency = prob_low
)

all_llm_scores <- numeric(0)
all_expert_scores <- numeric(0)

for (i in 1:18) {
  current_item <- subset(optiondata, itemID == paste0("item", i))
  current_item <- current_item[order(current_item$rank), ]  
  current_item$expert_score <- c(2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0)  
  current_item <- current_item[order(current_item$LLM), ]  
  current_item$LLM_score <- c(2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0)
  
  all_llm_scores <- c(all_llm_scores, current_item$LLM_score)
  all_expert_scores <- c(all_expert_scores, current_item$expert_score)
}

conf_matrix <- table(all_llm_scores, all_expert_scores)

conf_matrix_df <- as.data.frame(as.table(conf_matrix))
colnames(conf_matrix_df) <- c("LLM", "Expert", "Frequency")

conf_matrix_PS <- conf_matrix_df %>%
  group_by(LLM) %>%
  mutate(Proportion = Frequency / sum(Frequency)) %>%
  ungroup()

p_matrix_PS <- ggplot(conf_matrix_PS, aes(x = LLM, y = Expert)) +
  geom_tile(aes(fill = Proportion), color = "black") +  
  geom_text(aes(label = scales::percent(Proportion, accuracy = 0.1)), color = "black", size = 3) + 
  scale_fill_gradient(
    low = "white", 
    high = "orange", 
    name = " ",
    labels = scales::percent,  
    limits = c(0, 1),         
    breaks = seq(0, 1, by = 0.2) 
  ) + 
  labs(
    title = "Problem Solving",
    x = "ERNIE 4.0 Score",
    y = "Expert Score"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 11),
    axis.title.x = element_text(size = 9),                  
    axis.title.y = element_text(size = 9),
    legend.position = "none"
  )
                      
p_matrix_PS

# SO

optiondata<-read.xlsx('SO_new_options.xlsx')

item1 <- subset(optiondata, ID == "new_r1_1")
psych::ICC(item1[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.97

item2 <- subset(optiondata, ID == "new_r1_2")
psych::ICC(item2[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.98

item3 <- subset(optiondata, ID == "new_r1_3")
psych::ICC(item3[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.98

item4 <- subset(optiondata, ID == "new_r1_4")
psych::ICC(item4[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.98

item5 <- subset(optiondata, ID == "new_r1_5")
psych::ICC(item5[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) #0.97

item6 <- subset(optiondata, ID == "new_r1_6")
psych::ICC(item6[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) #0.98

item7 <- subset(optiondata, ID == "new_r2_1")
psych::ICC(item7[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) #0.97

item8 <- subset(optiondata, ID == "new_r2_2")
psych::ICC(item8[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) #0.99

item9 <- subset(optiondata, ID == "new_r2_3")
psych::ICC(item9[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) #0.98

item10 <- subset(optiondata, ID == "new_r2_4")
psych::ICC(item10[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) #0.99

item11 <- subset(optiondata, ID == "new_r2_5")
psych::ICC(item11[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) #0.98

item12 <- subset(optiondata, ID == "new_r2_6")
psych::ICC(item12[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) #0.98

item13 <- subset(optiondata, ID == "new_r3_1")
psych::ICC(item13[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) #0.98

item14 <- subset(optiondata, ID == "new_r3_2")
psych::ICC(item14[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) #0.97

item15 <- subset(optiondata, ID == "new_r3_3")
psych::ICC(item15[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) #0.98

item16 <- subset(optiondata, ID == "new_r3_4")
psych::ICC(item16[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) #0.97

item17 <- subset(optiondata, ID == "new_r3_5")
psych::ICC(item17[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) #0.98

item18 <- subset(optiondata, ID == "new_r3_6")
psych::ICC(item18[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) #0.98

optiondata <- optiondata %>%
  group_by(itemID) %>%
  mutate(
    rank = row_number(mean)  
  ) %>%
  ungroup()

#write.xlsx(optiondata,file='sorted_option.xlsx')

prob_high <- numeric(18)
prob_medium <- numeric(18)
prob_low <- numeric(18)

for (i in 1:18) {
  current_item <- subset(optiondata, itemID == paste0("item", i))
  current_item <- current_item[order(current_item$rank), ]  
  current_item$expert_score <- c(2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0)  
  current_item <- current_item[order(current_item$LLM), ]  
  current_item$LLM_score <- c(2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0)
  
  high_score_items <- subset(current_item, LLM_score == 2)
  matching_high <- sum(high_score_items$expert_score == 2)  
  prob_high[i] <- matching_high / nrow(high_score_items)
  
  medium_score_items <- subset(current_item, LLM_score == 1)
  matching_medium <- sum(medium_score_items$expert_score == 1)  
  prob_medium[i] <- matching_medium / nrow(medium_score_items)
  
  low_score_items <- subset(current_item, LLM_score == 0)
  matching_low <- sum(low_score_items$expert_score == 0)  
  prob_low[i] <- matching_low / nrow(low_score_items)
}

prob_high_df <- as.data.frame(prob_high)
prob_medium_df <- as.data.frame(prob_medium)
prob_low_df <- as.data.frame(prob_low)

consistency_results <- data.frame(
  itemID = paste0("item", 1:18),
  high_score_consistency = prob_high,
  medium_score_consistency = prob_medium,
  low_score_consistency = prob_low
)


all_llm_scores <- numeric(0)
all_expert_scores <- numeric(0)

for (i in 1:18) {
  current_item <- subset(optiondata, itemID == paste0("item", i))
  current_item <- current_item[order(current_item$rank), ]  
  current_item$expert_score <- c(2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0)  
  current_item <- current_item[order(current_item$LLM), ]  
  current_item$LLM_score <- c(2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0)
  
  all_llm_scores <- c(all_llm_scores, current_item$LLM_score)
  all_expert_scores <- c(all_expert_scores, current_item$expert_score)
}

conf_matrix <- table(all_llm_scores, all_expert_scores)

conf_matrix_df <- as.data.frame(as.table(conf_matrix))
colnames(conf_matrix_df) <- c("LLM", "Expert", "Frequency")

conf_matrix_SO <- conf_matrix_df %>%
  group_by(LLM) %>%
  mutate(Proportion = Frequency / sum(Frequency)) %>%
  ungroup()

p_matrix_SO <- ggplot(conf_matrix_SO, aes(x = LLM, y = Expert)) +
  geom_tile(aes(fill = Proportion), color = "black") +  
  geom_text(aes(label = scales::percent(Proportion, accuracy = 0.1)), color = "black", size = 3) + 
  scale_fill_gradient(
    low = "white", 
    high = "orange", 
    name = " ",
    labels = scales::percent,  # 将标签格式化为百分比
    limits = c(0, 1),          # 设置值的范围
    breaks = seq(0, 1, by = 0.2) # 设置刻度位置
  ) + 
  labs(
    title = "Student Orientation",
    x = "ERNIE 4.0 Score",
    y = "Expert Score"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 11),
    axis.title.x = element_text(size = 9),                  
    axis.title.y = element_text(size = 9),
    legend.position = "none"
  )

print(p_matrix_SO)

grid.arrange(p_matrix_PS,p_matrix_SO,ncol=2)

```


```{r adapted options}

# PS

PS_adp_opt <- read.xlsx('PS_adapted_options.xlsx')

psych::ICC(PS_adp_opt[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.92

PS_adp_opt <- PS_adp_opt %>%
  group_by(scenario_id) %>%
  mutate(
    SME = case_when(
      expert == max(expert) ~ 2,
      expert == min(expert) ~ 0,
      TRUE ~ 1 
    )
  ) %>%
  ungroup() 


# consistency between LLM and experts

conf_matrix_PS <- table(PS_adp_opt$LLM_score, PS_adp_opt$SME)

conf_matrix_ps <- as.data.frame(as.table(conf_matrix_PS))
colnames(conf_matrix_ps) <- c("ERNIE", "SME", "Frequency")

conf_matrix_ps <- conf_matrix_ps %>%
  group_by(ERNIE) %>%
  mutate(Proportion = Frequency / sum(Frequency)) %>%
  ungroup()

p_matrix_ps <- ggplot(conf_matrix_ps, aes(x = ERNIE, y = SME)) +
  geom_tile(aes(fill = Proportion), color = "black") +  
  geom_text(aes(label = scales::percent(Proportion, accuracy = 0.1)), color = "black", size = 3) + 
  scale_fill_gradient(low = "white", high = "skyblue", name = " ",
    labels = scales::percent, 
    limits = c(0, 1),  
    breaks = seq(0, 1, by = 0.2) 
  ) + 
  labs(
    title = "Problem Solving",
    x = "ERNIE 4.0 Score",
    y = "SME Score",
    limits = c(0, 1), 
    breaks = seq(0, 1, by = 0.2),
    labels = scales::percent
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 11),  
    axis.title.x = element_text(size = 9),  
    axis.title.y = element_text(size = 9),
    legend.position = "none"
  )


# SO

SO_adp_opt <- read.xlsx('SO_adapted_options.xlsx')

psych::ICC(SO_adp_opt[,c("expert1","expert2","expert3","expert4","expert5","expert6","expert7","expert8","expert9")]) # 0.95

SO_adp_opt <- SO_adp_opt %>%
  group_by(scenario_id) %>%
  mutate(
    SME = case_when(
      expert == max(expert) ~ 2, 
      expert == min(expert) ~ 0, 
      TRUE ~ 1 
    )
  ) %>%
  ungroup() 

conf_matrix_SO <- table(SO_adp_opt$LLM_score, SO_adp_opt$SME)

conf_matrix_so <- as.data.frame(as.table(conf_matrix_SO))
colnames(conf_matrix_so) <- c("ERNIE", "SME", "Frequency")

conf_matrix_so <- conf_matrix_so %>%
  group_by(ERNIE) %>%
  mutate(Proportion = Frequency / sum(Frequency)) %>%
  ungroup()

p_matrix_so <- ggplot(conf_matrix_so, aes(x = ERNIE, y = SME)) +
  geom_tile(aes(fill = Proportion), color = "black") +  
  geom_text(aes(label = scales::percent(Proportion, accuracy = 0.1)), color = "black", size = 3) + 
  scale_fill_gradient(low = "white", high = "skyblue", name = " ",
    labels = scales::percent,  
    limits = c(0, 1),   
    breaks = seq(0, 1, by = 0.2) 
  ) + 
  labs(
    title = "Student Orientation",
    x = "ERNIE 4.0 Score",
    y = "SME Score",
    limits = c(0, 1), 
    breaks = seq(0, 1, by = 0.2),
    labels = scales::percent 
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 11),
    axis.title.x = element_text(size = 9),                  
    axis.title.y = element_text(size = 9),
    legend.position = "none"
  )

grid.arrange(p_matrix_PS,p_matrix_SO,p_matrix_ps,p_matrix_so,ncol=4)

```

